### PR TITLE
Remove announcement enter key

### PR DESCRIPTION
**Pull request by SnowyNate**
As requested, removed ability to use <ENTER> key to make an announcement, and changed functionality to add a line.

### CODE REVIEW

**Comment by TheEgghead27** [comment]
Life protip: if you use one of the words in the [list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), you can automagically link an issue that will be closed when the PR is merged -- "fixes #129" for instance

Alternatively you can edit that in the side bar under "Development" but that's not as fun :P

**Comment by SnowyNate** [comment]
> Life protip: if you use one of the words in the [list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests), you can automagically link an issue that will be closed when the PR is merged -- "fixes #129" for instance
> 
> Alternatively you can edit that in the side bar under "Development" but that's not as fun :P

Awesome, thanks!

**Comment by SnowyNate** [comment]
Going to close this because my branch has a typo, along with many other issues with the PR.

**Comment by TheEgghead27** [comment]
Do note that you can rename branches, though I suppose it cannot hurt to rebase the changes

**Pull request closed without merging**
